library(shiny)
library(terra)
library(tidyverse)
library(sf)
library(ggplot2)
library(plotly)
library(rnaturalearth)
library(rnaturalearthdata)
library(scales)
library(patchwork)

# --- 1. Configuration & Setup ---

# Define where the app should look for predictions
# In Shinylive, this is relative to the app.R file
preds_path <- "predictions"

# Load base map data
world <- ne_countries(scale = "medium", returnclass = "sf")

# Load Polygons (Graceful failure if missing)
tryCatch({
  fishing_buffer <- sf::st_read("data/fishing_buffer.gpkg")
  hatched_area   <- sf::st_read("data/hatched_area.gpkg")
  desoto_canyon  <- sf::st_read("data/desotocanyon_restricted.shp")
}, error = function(e) {
  fishing_buffer <- NULL; hatched_area <- NULL; desoto_canyon <- NULL
})

# --- Species Lists ---
species_to_predict <- c(
  "tuna_yellowfin", "swordfish", "wahoo", "dolphin_fish_mahi_mahi",
  "tuna_bluefin", "marlin_blue", "skipjack", "tuna_bigeye", 
  "shark_silky", "shark_mako_shortfin", "sailfish", "marlin_white"
)

protected_species_to_predict <- c("manta_ray") 

# --- UI ---
ui <- fluidPage(
  titlePanel("Live Species Distribution and Overlap Explorer"),
  sidebarLayout(
    sidebarPanel(
      h4("1. Model Configuration"),
      
      radioButtons("model_set_type", "Select Model Set:",
                   choices = c("Pelagic Longline Fishery" = "Fishery",
                               "Protected Species Distribution" = "Protected_Species"),
                   selected = "Fishery"),
      
      uiOutput("target_or_species_selector"),
      
      # Date Selector (Dynamic based on available files)
      uiOutput("date_selector_ui"),
      
      hr(),
      h4("Map Layers"),
      checkboxInput("show_fishing_area", "Highlight Historical Fishing Area", value = FALSE),
      checkboxInput("show_desoto_canyon", "Highlight DeSoto Canyon Closed Area", value = FALSE),
      
      hr(),
      p("Displaying offline predictions generated by the GitHub Actions pipeline.")
    ),
    
    mainPanel(
      tabsetPanel(id = "main_tabs",
                  tabPanel("Single Layer Map",
                           p("Select a layer to display."),
                           fluidRow(
                             column(12, selectInput("fisheries_layer", "Select Species Prediction", choices = ""))
                           ),
                           plotlyOutput("distPlot", height = "600px"),
                           downloadButton("downloadSingleMap", "Download as GeoTIFF")
                  ),
                  
                  tabPanel("Integrated Multispecies Map",
                           p("Adjust weights to explore predictive surface. (Fishery Only)"),
                           sidebarLayout(
                             sidebarPanel(
                               h4("Target Species Weights"),
                               sliderInput("weight_yft", "Yellowfin Tuna:", min = 0, max = 2, value = 1.0, step = 0.1),
                               sliderInput("weight_swo", "Swordfish:", min = 0, max = 2, value = 0.9, step = 0.1),
                               sliderInput("weight_wah", "Wahoo:", min = 0, max = 2, value = 0.7, step = 0.1),
                               sliderInput("weight_mah", "Mahi Mahi:", min = 0, max = 2, value = 0.6, step = 0.1),
                               sliderInput("weight_skj", "Skipjack Tuna:", min = 0, max = 2, value = 0.0, step = 0.1),
                               sliderInput("weight_bet", "Bigeye Tuna:", min = 0, max = 2, value = 0.0, step = 0.1),
                               hr(),
                               h4("Bycatch Species Weights"),
                               sliderInput("weight_bft", "Bluefin Tuna:", min = 0, max = 2, value = 1.5, step = 0.1),
                               sliderInput("weight_bM", "Blue Marlin:", min = 0, max = 2, value = 1.5, step = 0.1), 
                               sliderInput("weight_ssy", "Silky Shark:", min = 0, max = 2, value = 0.0, step = 0.1),
                               sliderInput("weight_smk", "Shortfin Mako Shark:", min = 0, max = 2, value = 0.0, step = 0.1),
                               sliderInput("weight_sfi", "Sailfish:", min = 0, max = 2, value = 0.0, step = 0.1),
                               sliderInput("weight_wma", "White Marlin:", min = 0, max = 2, value = 0.0, step = 0.1)
                             ),
                             mainPanel(
                               plotlyOutput("integratedPlot", height = "600px"),
                               downloadButton("downloadIntegratedMap", "Download as GeoTIFF")
                             )
                           )
                  )
      )
    )
  )
)

# --- Server ---
server <- function(input, output, session) {
  
  # 1. Load Data (Scans folder for TIFs)
  map_data <- reactive({
    # List all TIF files
    files <- list.files(preds_path, pattern = "^PRED_.*\\.tif$", full.names = TRUE)
    
    if (length(files) == 0) return(NULL)
    
    # Initialize Structure
    data_struct <- list()
    
    for (f in files) {
      fname <- basename(f)
      
      # Parse Date (YYYY-MM-DD)
      date_str <- str_extract(fname, "\\d{4}-\\d{2}-\\d{2}")
      if(is.na(date_str)) next
      
      # Lazy Load Raster (Fast)
      r <- rast(f)
      
      # Parse Type & Species from Filename
      # Remove Prefix: PRED_2025-12-19_
      rest <- sub(paste0("PRED_", date_str, "_"), "", fname)
      rest <- sub(".tif$", "", rest)
      
      if (grepl("MANTA_RAY", rest)) {
        # Protected Species Logic
        # Structure: Date -> Protected_Species -> manta_ray -> Raster
        if (is.null(data_struct[[date_str]])) data_struct[[date_str]] <- list()
        if (is.null(data_struct[[date_str]]$Protected_Species)) data_struct[[date_str]]$Protected_Species <- list()
        
        # Key: "manta_ray" (lowercase for UI consistency if preferred)
        data_struct[[date_str]]$Protected_Species[["manta_ray"]] <- r
        
      } else {
        # Fishery Logic
        # Detect Objective
        obj <- if (grepl("Swordfish_Target", rest)) "Swordfish_Target" else "Yellowfin_Target"
        
        # Clean Species Name
        sp <- sub(paste0("_", obj, "_final_ensemble"), "", rest)
        
        # Structure: Date -> Fishery -> Objective -> Stack of Species
        if (is.null(data_struct[[date_str]])) data_struct[[date_str]] <- list()
        if (is.null(data_struct[[date_str]]$Fishery)) data_struct[[date_str]]$Fishery <- list()
        
        # Add to stack (create if missing, add if exists)
        if (is.null(data_struct[[date_str]]$Fishery[[obj]])) {
          data_struct[[date_str]]$Fishery[[obj]] <- r
          names(data_struct[[date_str]]$Fishery[[obj]]) <- sp
        } else {
          # Append layer
          current_stack <- data_struct[[date_str]]$Fishery[[obj]]
          add(current_stack) <- r
          names(current_stack)[nlyr(current_stack)] <- sp
          data_struct[[date_str]]$Fishery[[obj]] <- current_stack
        }
      }
    }
    
    return(data_struct)
  })
  
  # 2. Dynamic UI: Date Selector
  output$date_selector_ui <- renderUI({
    req(map_data())
    available_dates <- names(map_data())
    #Sort descending (newest first)
    available_dates <- sort(available_dates, decreasing = TRUE)
    
    selectInput("selected_date", "Select Prediction Date:", choices = available_dates, selected = available_dates[1])
  })
  
  # 3. Dynamic UI: Objectives
  output$target_or_species_selector <- renderUI({
    req(input$model_set_type)
    if (input$model_set_type == "Fishery") {
      selectInput("display_objective", "Select Fishery Target:",
                  choices = c("Swordfish Target" = "Swordfish_Target",
                              "Yellowfin Target" = "Yellowfin_Target"))
    } else {
      selectInput("display_objective", "Select Species Model:",
                  choices = c("Manta Ray" = "manta_ray"))
    }
  })
  
  # 4. Get Active Stack
  active_stack <- reactive({
    req(map_data(), input$selected_date, input$model_set_type, input$display_objective)
    
    # Traverse the list: Date -> Type -> Objective
    # Defensive check
    d_date <- map_data()[[input$selected_date]]
    if(is.null(d_date)) return(NULL)
    
    d_type <- d_date[[input$model_set_type]]
    if(is.null(d_type)) return(NULL)
    
    stack <- d_type[[input$display_objective]]
    req(stack)
    return(stack)
  })
  
  # 5. Update Layer Dropdown
  observeEvent(active_stack(), {
    req(active_stack())
    layer_names <- names(active_stack())
    # Create nice names (replace _ with space)
    display_names <- setNames(layer_names, gsub("_", " ", layer_names))
    
    updateSelectInput(session, "fisheries_layer", choices = display_names)
  })
  
  # 6. Plotting Logic
  output$distPlot <- renderPlotly({
    req(active_stack(), input$fisheries_layer)
    
    r <- active_stack()[[input$fisheries_layer]]
    df <- as.data.frame(r, xy=TRUE, na.rm=TRUE)
    colnames(df)[3] <- "value"
    
    p <- ggplot(df, aes(x=x, y=y, fill=value)) +
      geom_tile() +
      scale_fill_viridis_c(option="D", name="Probability") +
      geom_sf(data=world, inherit.aes=FALSE, fill="gray80") +
      coord_sf(xlim = c(-100, -80), ylim = c(18, 31), expand = FALSE) +
      theme_minimal() +
      labs(title = paste(input$fisheries_layer, "-", input$selected_date))
    
    # Add Polygons
    if (input$show_fishing_area && !is.null(hatched_area)) {
      p <- p + geom_sf(data=hatched_area, inherit.aes=FALSE, fill='grey20', alpha=0.4, color=NA)
    }
    if (input$show_desoto_canyon && !is.null(desoto_canyon)) {
      p <- p + geom_sf(data=desoto_canyon, inherit.aes=FALSE, fill="red", alpha=0.3)
    }
    
    ggplotly(p)
  })
  
  # 7. Integrated Map Logic
  integrated_surface_reactive <- reactive({
    req(input$model_set_type == "Fishery", active_stack())
    
    s <- active_stack()
    valid_names <- names(s)
    
    # Helper to get weight safely
    get_w <- function(id) { w <- input[[id]]; if(is.null(w)) 0 else w }
    
    # Weights Map
    w_map <- c(
      "tuna_yellowfin" = get_w("weight_yft"), "swordfish" = get_w("weight_swo"),
      "wahoo" = get_w("weight_wah"), "dolphin_fish_mahi_mahi" = get_w("weight_mah"),
      "skipjack" = get_w("weight_skj"), "tuna_bigeye" = get_w("weight_bet")
    )
    b_map <- c(
      "tuna_bluefin" = get_w("weight_bft"), "marlin_blue" = get_w("weight_bM"),
      "shark_silky" = get_w("weight_ssy"), "shark_mako_shortfin" = get_w("weight_smk"),
      "sailfish" = get_w("weight_sfi"), "marlin_white" = get_w("weight_wma")
    )
    
    # Calculate Scores
    target_score <- s[[1]] * 0
    total_w_t <- 0
    
    for(sp in names(w_map)) {
      if(sp %in% valid_names && w_map[[sp]] > 0) {
        # Thresholding (optional, from original app)
        layer <- s[[sp]]; layer[layer < 0.25] <- 0
        target_score <- target_score + (layer * w_map[[sp]])
        total_w_t <- total_w_t + w_map[[sp]]
      }
    }
    if(total_w_t > 0) target_score <- target_score / total_w_t
    
    bycatch_score <- s[[1]] * 0
    for(sp in names(b_map)) {
      if(sp %in% valid_names && b_map[[sp]] > 0) {
        bycatch_score <- bycatch_score + (s[[sp]] * b_map[[sp]])
      }
    }
    
    final <- target_score - bycatch_score
    names(final) <- "Integrated_Score"
    return(final)
  })
  
  output$integratedPlot <- renderPlotly({
    req(integrated_surface_reactive())
    r <- integrated_surface_reactive()
    df <- as.data.frame(r, xy=TRUE, na.rm=TRUE)
    
    p <- ggplot(df, aes(x=x, y=y, fill=Integrated_Score)) +
      geom_tile() +
      scale_fill_gradient2(low = "darkred", mid = "white", high = "darkblue", midpoint = 0) +
      geom_sf(data=world, inherit.aes=FALSE, fill="gray80") +
      coord_sf(xlim = c(-100, -80), ylim = c(18, 31), expand = FALSE) +
      theme_minimal() +
      labs(title = paste("Integrated Map -", input$selected_date))
    
    ggplotly(p)
  })
  
  # Downloads
  output$downloadSingleMap <- downloadHandler(
    filename = function() { paste0(input$fisheries_layer, "_", input$selected_date, ".tif") },
    content = function(file) {
      req(active_stack(), input$fisheries_layer)
      writeRaster(active_stack()[[input$fisheries_layer]], file, overwrite=TRUE)
    }
  )
  
  output$downloadIntegratedMap <- downloadHandler(
    filename = function() { paste0("Integrated_", input$selected_date, ".tif") },
    content = function(file) {
      req(integrated_surface_reactive())
      writeRaster(integrated_surface_reactive(), file, overwrite=TRUE)
    }
  )
}

shinyApp(ui, server)
