name: Predict Gulf of Mexico

on:
  workflow_run:
    workflows: ["Download CMEMS data"]
    types: [completed]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  predict-gulf:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.3'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgdal-dev libgeos-dev libproj-dev libnetcdf-dev libudunits2-dev libharfbuzz-dev libfribidi-dev

    - name: Install R Dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache: always
        packages: |
          any::dplyr
          any::terra
          any::sf
          any::ggplot2
          any::tidyterra
          any::remotes
          any::googledrive
          any::stringr
          any::fmesher
          any::BiocManager

    - name: Install INLA & inlabru
      run: |
        Rscript -e "BiocManager::install(c('graph', 'Rgraphviz'), update=FALSE, ask=FALSE)"
        Rscript -e "install.packages('INLA', repos=c(getOption('repos'), INLA='https://inla.r-inla-download.org/R/stable'), dep=TRUE)"
        Rscript -e "remotes::install_version('inlabru', version='2.12.0', repos='https://cloud.r-project.org')"
        Rscript -e "remotes::install_version('xgboost', version='1.7.8.1', repos='https://cloud.r-project.org')"

    - name: Run Leatherback Prediction
      run: Rscript model_prediction/R/predict_leatherback_gulf.R

    - name: Commit and Push
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add model_prediction/gulf/predictions/*.tif
        git add model_prediction/gulf/predictions/*.png
        if git diff --staged --quiet; then
          echo "No changes."
        else
          git commit -m "Update Gulf Predictions [$(date +'%Y-%m-%d')]"
          git push origin main
        fi
